name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-to-github-releases:
    runs-on: windows-latest
    env:
      Project_Path: SimpleTwitchEmoteSounds/SimpleTwitchEmoteSounds.csproj
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Application
        run: dotnet publish ${{ env.Project_Path }} -c Release -o ./publish -r win-x64 --self-contained false -p:PublishSingleFile=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleTwitchEmoteSounds
          path: ./publish