name: Deploy

on:
  # Run CI when a new branch or tag is created
  create:
    # only run if the tag is a supported version tag
    tags:
      - "v*.*.*"
  # Run CI when a new commit is pushed
  push:
    branches:
      - master
      - feature-nsis-installer

jobs:
  push-deploy:
    strategy:
        matrix:
          os: [ubuntu-latest,windows-latest]
          portable: [true, false]
    runs-on: ${{ matrix.os }}
    env:
      Project_Path: SimpleTwitchEmoteSounds/SimpleTwitchEmoteSounds.csproj
      Output_Path: publish
      Dotnet_Publish_Runtime: ${{ startsWith(matrix.os, 'windows') && 'win' || 'linux' }}-x64
      # Constants with which the non portable install release is compiled

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Application (${{ matrix.portable && 'portable' || 'installed' }})
        run: dotnet publish ${{ env.Project_Path }} -o ${{ env.Output_Path }} -r ${{ env.Dotnet_Publish_Runtime }} ${{ env.Dotnet_Publish_Options }} ${{ env.Dotnet_Publish_Options_DefineConstants }}
        env:
          Dotnet_Publish_Options: -c Release -p:PublishSingleFile=true -p:DebugType=none -p:PublishReadyToRun=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained false
          Dotnet_Publish_Options_DefineConstants: ${{ matrix.portable == false && '-p:DefineConstants="CUSTOM_FEATURE_INSTALLED"' || '' }}

      # makensis is installed per default
      - name: Create NSIS Installer
        if: startsWith(matrix.os, 'windows') && matrix.portable == false
        run: makensis windows_installer.nsi
        working-directory: nsis

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleTwitchEmoteSounds-${{ env.Dotnet_Publish_Runtime }}-${{ matrix.portable && 'portable' || 'installed' }}
          path: ${{ env.Output_Path }}
  create-github-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Only create a GitHub release if a new tag was pushed that starts with v
    # and if the build step was successful
    needs: push-deploy
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Download build step artifact linux-x64 (portable)
      uses: actions/download-artifact@v4
      with:
        name: SimpleTwitchEmoteSounds-linux-x64-portable
        path: publish_linux-x64-portable
    # -> publish_linux-x64-portable
    #    |
    #    +- SimpleTwitchEmoteSounds
    - name: Download build step artifact win-x64 (portable)
      uses: actions/download-artifact@v4
      with:
        name: SimpleTwitchEmoteSounds-win-x64-portable
        path: publish_win-x64-portable
    # -> publish_win-x64-portable
    #    |
    #    +- SimpleTwitchEmoteSounds.exe
    - name: Download build step artifact win-x64
      uses: actions/download-artifact@v4
      with:
        name: SimpleTwitchEmoteSounds-win-x64-installed
        path: publish_win-x64-installed
    # -> publish_win-x64-installed
    #    |
    #    +- SimpleTwitchEmoteSounds.exe
    #    +- SimpleTwitchEmoteSounds_installer.exe
    - name: Generate Changelog
      run: |
        echo "Linux and Windows binary require the [.NET runtime](https://dotnet.microsoft.com/en-us/download) to run." > ${{ github.workspace }}-CHANGELOG.txt
        echo "Linux requires the binary to be marked as executable (\`chmod +x SimpleTwitchEmoteSounds\`)." >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "**\`sha256sum\`s:**" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- \`SimpleTwitchEmoteSounds\` (Linux binary): \`$(sha256sum ./publish_linux-x64-portable/SimpleTwitchEmoteSounds | awk '{print $1}')\`" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- \`SimpleTwitchEmoteSounds.exe\` (Windows binary): \`$(sha256sum ./publish_win-x64-portable/SimpleTwitchEmoteSounds.exe | awk '{print $1}')\`" >> ${{ github.workspace }}-CHANGELOG.txt
        echo "- \`SimpleTwitchEmoteSounds_installer.exe\` (Windows installer binary): \`$(sha256sum ./publish_win-x64-installed/SimpleTwitchEmoteSounds_installer.exe | awk '{print $1}')\`" >> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: ${{ github.workspace }}-CHANGELOG.txt
        generate_release_notes: true
        files: |
          ./publish_linux-x64-portable/SimpleTwitchEmoteSounds
          ./publish_win-x64-portable/SimpleTwitchEmoteSounds.exe
          ./publish_win-x64-installed/SimpleTwitchEmoteSounds_installer.exe
