name: Deploy

on:
  # Run CI when a new branch or tag is created
  create:
    # only run if the tag is a supported version tag
    tags:
      - "v*.*.*"
  # Run CI when a new commit is pushed
  push:
    branches:
      - master

jobs:
  push-deploy:
    strategy:
        matrix:
          os: [ubuntu-latest,windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      Project_Path: SimpleTwitchEmoteSounds/SimpleTwitchEmoteSounds.csproj
      Dotnet_Publish_Runtime: ${{ startsWith(matrix.os, 'windows') && 'win' || 'linux' }}-x64
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish Application
        run: dotnet publish ${{ env.Project_Path }} -c Release -o ./publish -r ${{ env.Dotnet_Publish_Runtime }} -p:PublishSingleFile=true -p:DebugType=none -p:PublishReadyToRun=false -p:IncludeNativeLibrariesForSelfExtract=true --self-contained false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleTwitchEmoteSounds-${{ env.Dotnet_Publish_Runtime }}
          path: ./publish
  create-github-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    # Only create a GitHub release if a new tag was pushed that starts with v
    # and if the build step was successful
    needs: push-deploy
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Download build step artifact linux-x64
      uses: actions/download-artifact@v4
      with:
        name: SimpleTwitchEmoteSounds-linux-x64
        path: publish_linux-x64
    # -> publish_linux-x64
    #    |
    #    +- SimpleTwitchEmoteSounds
    - name: Download build step artifact win-x64
      uses: actions/download-artifact@v4
      with:
        name: SimpleTwitchEmoteSounds-win-x64
        path: publish_win-x64
    # -> publish_win-x64
    #    |
    #    +- SimpleTwitchEmoteSounds.exe
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./publish_linux-x64/SimpleTwitchEmoteSounds
          ./publish_win-x64/SimpleTwitchEmoteSounds.exe
          ./pkgbuild/PKGBUILD
